name: epah
favicon: null
layout_spectrum: 0.05754787544719875
typography_spectrum: 0.58409303589724
title: EPAH
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.17993044550530612
  lightness: 0.05306292581371963
  saturation: 0.6277245720848441
  rhythmicContrast: 0.735238547436893
purpose: []
